version: "3"

services:
  hasty-gateway:
    build:
      context: ./hasty-gateway
      dockerfile: Dockerfile
    environment:
      - CONFIG=/config.json
      - LOG_LEVEL=debug
      - INSTRUMENTING=true
    volumes:
      - "./config/config-user.json:/config.json"
    ports:
      - "1234:8080"
    restart: always
    networks:
      - hasty

  hasty-auth:
    build:
      context: ./hasty-auth
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=debug
      - INSTRUMENTING=true
    ports:
      - "1235:8000"
    restart: always
    networks:
      - hasty

networks:
  hasty:
    external: true
